### ISSUE TITLE
Data-Annotation for mathematical equations

### ISSUE THREAD

**Issue by mohit-217** [win5923/TrOCR-Handwritten-Mathematical-Expression-Recognition#1]
hey @win5923 can you please help me ,how to annotate data of mathematical annotations for TR-OCR training.

**Comment by win5923** [comment]
Do you mean create a dataset? I didn't create it myself, I trained it using im2Latex100k's dataset.

**Comment by mohit-217** [comment]
![FCA(1)-3-0tensor(0 87984)782](https://user-images.githubusercontent.com/51528367/198872958-b127a5b5-fe98-498d-a0b7-66cee8e0a811.png)
![FCA(1)-15-3tensor(0 89289)844](https://user-images.githubusercontent.com/51528367/198872976-bcbbcf06-fdbe-4bde-9ddc-7da70d7a00a8.png)
![FCA(2)-15-1tensor(0 83787)549](https://user-images.githubusercontent.com/51528367/198872985-32a68df9-0042-4e0b-8f1f-10a8391bbe5d.png)
![FCA6-3-2tensor(0 88409)1942](https://user-images.githubusercontent.com/51528367/198873002-32019e19-bb98-4cc0-973f-5aac2571e259.png)

How i can annotate above data for training

**Comment by win5923** [comment]
Sorry, may not be able to help you,probably need to manually annotate.

**Comment by mohit-217** [comment]
Yes I will do it manually but how to annotate S^2 .Just wanted to ask you

**Comment by mohit-217** [comment]
How I need to annotate for these type of data.
1. 3 ( 7s+ 8 )
2. 5 (6s + 7)
3. s^2
4. s^2 + 3s + 1

These annotation is correct?
